baseURL = 'https://teobatman00.github.io/Minh-Duong-Blog/'
languageCode = 'vi'
defaultContentLanguage = 'vi'
languageName = 'Vietnamese'
title = 'Minh Dương Blog'
theme = "LoveIt"
googleAnalytics = 'G-400LBDPY77'
copyright = 'Minh Dương'
enableGitInfo = true

[frontmatter]
    lastmod = ["lastmod", ":git", "date", "publishDate"]

[menu]
[[menu.main]]
    identifier = 'About'
    name = 'Giới thiệu'
    url = 'introduction'
    weight = 1
[[menu.main]]
    identifier = 'Posts'
    name = 'Bài viết'
    url = 'posts'
    weight = 2
[[menu.main]]
    identifier = 'Categories'
    name = 'Thể loại'
    url = 'categories'
    weight = 3
[[menu.main]]
    identifier = 'Tags'
    name = 'Thẻ'
    url = 'tags'
    weight = 4
[[menu.main]]
    identifier = 'Contacts'
    name = 'Liên hệ'
    url = 'contacts'
    weight = 5


[params]
    description = 'Trang cá nhân Minh Dương'
    [params.home.profile]
        subtitle = 'Trang cá nhân Minh Dương'
        avatarURL = 'https://ps.w.org/user-avatar-reloaded/assets/icon-256x256.png?rev=2540745'
    [params.header.title]
        name = 'Minh Dương Blog'
    [params.app]
        title = 'Minh Dương Blog'
    [params.footer]
        license = 'Bản quyền thuộc về Minh Dương Blog'
        hugo = false
        custom = 'Minh Dương Blog'
    [params.search]
        enable = true
        type = "algolia"
        contentLength = 4000
        placeholder = "Tìm kiếm tại đây"
        [params.search.algolia]
            index = "personal_blog"
            appID = "LM3W7U79VA"
            searchKey =  "ca8c0c3c79b2f069d4bd6f5d1dbfd247"
    [params.page.math]
        enable = true
    [params.social]
        GitHub = 'teobatman00'
        Phone = '0916310208'
        Email = 'minhduongb97@gmail.com'
    [params.page.comment]
        enable = true
        [params.page.comment.utterances]
            enable = true
            repo = "teobatman00/Minh-Duong-Blog"

[author]
    name = 'Minh Dương'
    email = 'minhduongb97@gmail.com'
[minify]
    minifyOutput = true
[sitemap]
    changefreq = 'hourly'

[markup]
    [markup.highlight]
        noClasses = false

[outputs]
    home = ["HTML", "RSS", "JSON"]
