baseURL = 'https://teobatman00.github.io/Minh-Duong-Blog/'
languageCode = 'vi'
title = 'Minh Dương Blog'
theme = "LoveIt"

[menu]
[[menu.main]]
    identifier = 'About'
    name = 'Về tôi'
    url = 'about'
[[menu.main]]
    identifier = 'Posts'
    name = 'Bài viết'
    url = 'posts'
[[menu.main]]
    identifier = 'Categories'
    name = 'Thể loại'
    url = 'categories'
[[menu.main]]
    identifier = 'Contacts'
    name = 'Liên hệ'
    url = 'contacts'
[[menu.main]]
    identifier = 'Tags'
    name = 'Thẻ'
    url = 'tags'


[params]
    author = 'Minh Dương'
    home.profile.subtitle = 'Trang cá nhân Minh Dương'
    [params.header.title]
        name = 'Minh Dương Blog'
    [params.app]
        title = 'Minh Dương Blog'
    [params.footer]
        license = 'Bản quyền thuộc về Minh Dương Blog'
        hugo = false
        custom = 'Minh Dương Blog'
    [params.search]
        enable = true
        contentLength = 4000
        placeholder = "Tìm kiếm tại đây"
    [params.page.math]
        enable = true
    [params.social]
        GitHub = 'https://github.com/teobatman00'
        Phone = '0916310208'
    [params.page.comment]
        enable = true
        [params.page.comment.utterances]
            enable = true
            repo = "teobatman00/Minh-Duong-Blog"
    [params.analytics]
        enable = true
        [params.analytics.google]
            id = "3762929097"

[author]
    name = 'Minh Duong'