baseURL = 'https://teobatman00.github.io/Minh-Duong-Blog/'
languageCode = 'vi'
title = 'Minh Dương Blog'
theme = "LoveIt"

[menu]
[[menu.main]]
    identifier = 'About'
    name = 'Về tôi'
    url = 'about'
[[menu.main]]
    identifier = 'Posts'
    name = 'Bài viết'
    url = 'posts'
[[menu.main]]
    identifier = 'Categories'
    name = 'Thể loại'
    url = 'categories'
[[menu.main]]
    identifier = 'Contacts'
    name = 'Liên hệ'
    url = 'contacts'
[[menu.main]]
    identifier = 'Tags'
    name = 'Thẻ'
    url = 'tags'


[params]
    author = 'Minh Dương'
    header.title.name = 'Minh Dương Blog'
    home.profile.subtitle = 'Trang cá nhân Minh Dương'
    footer.license = 'Bản quyền thuộc về Minh Dương'
    [params.search]
        enable = true
        contentLength = 4000
        placeholder = "Tìm kiếm tại đây"
    [params.page.math]
        enable = true
    [params.page.comment]
        enable = true
        [params.page.comment.utterances]
            enable = true
            repo = "teobatman00/Minh-Duong-Blog"

[author]
    name = 'Minh Duong'