baseURL = 'https://teobatman00.github.io/Minh-Duong-Blog/'
languageCode = 'vi'
defaultContentLanguage = 'vi'
languageName = 'Vietnamese'
title = 'Minh Dương Blog'
theme = "LoveIt"
googleAnalytics = 'G-400LBDPY77'
copyright = 'Minh Dương'
enableGitInfo = true

[frontmatter]
    lastmod = ["lastmod", ":git", "date", "publishDate"]

[menu]
[[menu.main]]
    identifier = 'About'
    name = 'Về tôi'
    url = 'about'
[[menu.main]]
    identifier = 'Posts'
    name = 'Bài viết'
    url = 'posts'
[[menu.main]]
    identifier = 'Categories'
    name = 'Thể loại'
    url = 'categories'
[[menu.main]]
    identifier = 'Contacts'
    name = 'Liên hệ'
    url = 'contacts'
[[menu.main]]
    identifier = 'Tags'
    name = 'Thẻ'
    url = 'tags'


[params]
    description = 'Trang cá nhân Minh Dương'
    [params.home.profile]
        subtitle = 'Trang cá nhân Minh Dương'
    [params.header.title]
        name = 'Minh Dương Blog'
    [params.app]
        title = 'Minh Dương Blog'
    [params.footer]
        license = 'Bản quyền thuộc về Minh Dương Blog'
        hugo = false
        custom = 'Minh Dương Blog'
    [params.search]
        enable = true
        contentLength = 4000
        placeholder = "Tìm kiếm tại đây"
    [params.page.math]
        enable = true
    [params.social]
        GitHub = 'https://github.com/teobatman00'
        Phone = '0916310208'
        Email = 'minhduongb97@gmail.com'
    [params.page.comment]
        enable = true
        [params.page.comment.utterances]
            enable = true
            repo = "teobatman00/Minh-Duong-Blog"

[author]
    name = 'Minh Dương'
    email = 'minhduongb97@gmail.com'
[minify]
    minifyOutput = true
[sitemap]
    changefreq = 'hourly'